---
# inspo: https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml
name: update flake.lock
on:
  schedule:
    # 03:00 UTC, any date, month, day of week - ONLY FEB FOR NOW UNTIL I GET INTERNET AT HOME
    - cron: 0 3 * 2 *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Daily bot flake.lock update"
          commit_user_name: Flake Bot
          commit_options: --no-verify --signoff
          commit_author: Flake Bot <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
